### ISSUE TITLE
コードハイライトされてない

### ISSUE THREAD

**Issue by miyamoen** [elm-jp/guide#10]
なんで

**Comment by matsubara0507** [comment]
わからぬ、git book の設定とか？

**Comment by calmery** [comment]
DevTools でドキュメントのデータを見てみたのですが [gitbook.com](https://www.gitbook.com/) 上だと特定の言語以外は Plain Text として扱われてしまうみたいで，Elm も Plain Text となっている感じです．gitbook.com は内部的に [prismjs-components-loader](https://github.com/Soreine/prismjs-components-loader) の `common-components` を使っているようで，そこに Elm が含まれていないのが原因なのかなと．
```json
{
  "type": "code",
  "nodes": [{
    "kind": "block",
    "type": "code-tab",
    "data": {
      "syntax": "text"
    }
  }]
}
```
<img width="926" alt="screenshot" src="https://user-images.githubusercontent.com/12670155/44625861-36193e00-a94d-11e8-92e5-2128fe7aaa2d.png">

[Important differences - GitBook](https://docs.gitbook.com/v2-changes/important-differences#plugins) を見る限り，gitbook.com 上ではプラグインの追加もできないようなのでコードだけ Gist などで埋め込むか GitHub Pages などを使うなりする必要がありそうです．

**Comment by matsubara0507** [comment]
https://guide.elm-lang.org ではなんでハイライトされてるんだろ？と思ってたけど、そうか、向こうはオンプレ？自分で改造してるのか。

**Comment by calmery** [comment]
[guide.elm-lang.org](https://guide.elm-lang.org) は [legacy.gitbook.com](https://legacy.gitbook.com/) を使ってるみたいですね．[legacy.gitbook.com](https://legacy.gitbook.com/) だと `gitbook serve` したときと同じように表示されるみたいです．
[legacy.gitbook.com/@evancz](https://legacy.gitbook.com/@evancz)

**Comment by arowM** [comment]
なんと！ もし legacy のサポートがしばらく続くのであれば、本公開(noindexを外す）前に移行したいですね。
legacy って gitbook 的にどういう位置づけなんでしょう。。。

**Comment by calmery** [comment]
[I cannot create an account · GitBook Help Center](https://help.gitbook.com/accounts/i-cannot-create-an-account.html) にもありますが [legacy.gitbook.com](https://legacy.gitbook.com/) はもう新規でのアカウントの登録ができないようなので移行は難しいかもしれません．既にある組織には招待できるようですが legacy.gitbook.com には elm-jp はありませんし，新規に作成しようとすると [gitbook.com](https://www.gitbook.com/) での作成になります．
GitBook としては legacy.gitbook.com のサポートは続けるけど，これからは gitbook.com を使ってねという感じなのかなと．

**Comment by arowM** [comment]
う〜む。 そしたら GitHub Pages でサイトをServeしてプラグインとかで対応するのがよさそうですね〜

**Comment by arowM** [comment]
GitHub Pages に移行してハイライトされるようになりました！
