### ISSUE TITLE
text field の訳を決めたい

### ISSUE THREAD

**Issue by arowM** [elm-jp/guide#100]
related to https://github.com/elm-jp/guide/pull/88#discussion_r230575606

現在、対訳表では
> | テキスト入力 | text field |

になっていますが、 text input と紛らわしいのでほかにもっといい訳がありそうな気がします。

a. テキスト入力
b. テキストフィールド
c. テキスト入力欄
d. 文字入力欄

などみなさんのご意見をください m(_ _)m

僕は d が好きです。

**Comment by matsubara0507** [comment]
d 次点で c がしっくり来ます、個人的には

**Comment by miyamoen** [comment]
d?

**Comment by matsubara0507** [comment]
(ぼくのこと？ d が一番、c が二番って意味ですw)

**Comment by aratama** [comment]
個人的には私もdを推したいところですが、 https://guide.elm-lang.jp/architecture/ ではその前後が『ボタン』『チェックボックス』『ラジオボタン』とカタカナ語が並んでしまっているので、そこに『文字入力欄』が交じると違和感はあります。世間的にもbで定着しつつある感じはあるので、悩みますが無難にbに一票……。

**Comment by arowM** [comment]
それも完全にそのとおりなので b と d で迷っちゃいます。
僕は優柔不断なので誰かズパっとたすけてください。

**Comment by mather** [comment]
d「文字入力欄」だと `<input>` と `<textarea>` を混同しそうなので b「テキストフィールド」に一票。

**Comment by arowM** [comment]
よ〜し！ 流れがキテるからこの感じで「ダメ」って意見がなかったら b 「テキストフィールド」にしちゃいます！

あと、その流れで翻訳時のカタカナ語の採用基準として

* 日本語訳が浸透している用語はカタカナ語にしない
* 日本語訳よりもカタカナ語が十分に浸透していてグーグラビリティなども高い場合は無理に日本語訳をせずにカタカナ表記にする
* カタカナ語としても日本語としてもあまり浸透しておらず、パッと見で意味が分かる日本語訳もない場合はカタカナ語を推奨する

みたいなルールを追加しちゃおうと思います。

このルールについてもご意見があれば今のうちにお願いします！
