### ISSUE TITLE
"Commands and Subscriptions"の各チャプターの順番が違う

### ISSUE THREAD

**Issue by ikngtty** [elm-jp/guide#107]
元サイトでは`HTTP -> JSON -> Random -> Time`となっていますが、
翻訳サイトでは`Random -> Time -> JSON -> HTTP`となっています。
何か理由があるのでしょうか？

**Comment by arowM** [comment]
たぶん、原文の更新をまだ反映してないからだと思います！
ご指摘ありがとうございます 🌻

**Comment by arowM** [comment]
修正しました！
https://github.com/elm-jp/guide/pull/110/commits/3f65fc2ed9eb55cfb6be32292c708bbc46b26a75
