### ISSUE TITLE
不自然な文

### ISSUE THREAD

**Issue by yuta0801** [elm-jp/guide#127]
[言語の基礎](https://guide.elm-lang.jp/core_language.html)にあるレコードの説明の
```
もし10個のフィールドのうちのひとつを更新したとしたら、変更されていない残りの9個の値は新しいレコードも共有します。
```
という文が不自然で意味が伝わりにくいと思いました

もしすでに修正済みならそっと閉じていただけるとありがたいです...

**Comment by miyamoen** [comment]
#128 @yuta0801 よかったら確認お願いします

**Comment by yuta0801** [comment]
早速の修正ありがとうございます
