### ISSUE TITLE
"attribute" の訳を統一したい

### ISSUE THREAD

**Issue by gyokuro-iri** [elm-jp/guide#131]
"attribute" を

book/architecture/text_fields.md では「 属性」
book/architecture/buttons.md では「アトリビュート」
book/effects/time.md では「属性」
book/optimization/lazy.md では「属性」

と、それぞれ訳しています。

私は「属性」が好きです。短いから！
みなさんはどっちが好きですか？

**Comment by arowM** [comment]
僕も「属性」が好きです。

最近追加された「カタカナ語の採用基準」
* 日本語訳が浸透している用語はカタカナ語にしない
* 日本語訳よりもカタカナ語が十分に浸透していてグーグラビリティなども高い場合は無理に日本語訳をせずにカタカナ表記にする
* カタカナ語としても日本語としてもあまり浸透しておらず、パッと見で意味が分かる日本語訳もない場合はカタカナ語を推奨する

から考えても、あえてカタカナ語にしなくても「属性」が十分に浸透しているからです！

**Comment by gyokuro-iri** [comment]
なるほど！
この「カタカナ語の採用基準」は、PRを出すときに表示されるようになってるんですね。
私はPRを出したことがないので、はじめてみました。ありがとうございます！

**Comment by arowM** [comment]
たしかに！
あとでREADMEあたりに追加しておきます。

**Comment by matsubara0507** [comment]
属性 👌 
ここにも追加して欲しいっす
https://github.com/elm-jp/guide/blob/master/book/about_translation.md#訳語対応表

**Comment by arowM** [comment]
属性で良さそうな感じしますね！
@gyokuro-iri もしよければ、既存の「アトリビュート」と訳されている部分を「属性」に変更するPRをだしてもらえますか？

**Comment by gyokuro-iri** [comment]
了解しました。

既に、book/architecture/buttons.md は
miyamoenさんの指摘を受けて、
book/architecture/buttons.md の翻訳をされたr6eveさんが変更してくれてました！
他はアトリビュートになっているところはなさそうでした。

https://github.com/elm-jp/guide/pull/129/commits/a7a99b49a031b4cfb6c040fdb47fc960268120e2

**Comment by arowM** [comment]
ご確認ありがとうございます！！

対訳表への追加は、無慈悲なるmasterへの直接pushで対応しておきました。
42ca512c7800dfeb86cf565bd9c8c7fc92aee3da
