### ISSUE TITLE
install.md の Linux(原文ではAnywhere)を追従する (npm install が欠けている)

### ISSUE THREAD

**Issue by minekoa** [elm-jp/guide#149]
現状:

> * Linux — インストールガイド

原文:

> * Anywhere — direct download or npm

Linux -> Anywhere になり、npm インストールが追加、direct download のリンク先も変更されています

おそらく

https://github.com/evancz/guide.elm-lang.org/commit/36895d5aa95b1360a7729069cdcda014289249a0
https://github.com/evancz/guide.elm-lang.org/commit/92c26ed17babd3bbe64108a7d992b4acaba649a2

に日訳版がまだ追従していないのかと思います。

**Comment by arowM** [comment]
ありがとうございます！
僕が更新作業する時に見落としちゃったので修正しておきます。

**Comment by arowM** [comment]
修正完了しました！
