### ISSUE TITLE
guide/result.md の翻訳

### ISSUE THREAD

**Issue by RkEclair** [elm-jp/guide#156]

**Comment by arowM** [comment]
https://github.com/elm-jp/guide/pull/123
こちらとは別のページですか？

**Comment by RkEclair** [comment]
検索で出てこなかったので……失礼しました

**Comment by arowM** [comment]
いえいえ〜 せっかく翻訳していただいたものがかぶるのを防げてよかったです！

このページ、ずっと英語のままですみません m(_ _)m
ping @miyamoen
