### ISSUE TITLE
type alias の訳を「型エイリアス」に変更したい

### ISSUE THREAD

**Issue by arowM** [elm-jp/guide#181]
現在は「型の別名」と訳していますが、「型エイリアス」の方が以下の点で優れていると思います。

1. ひとかたまりの固有名詞感がでて訳文が読みやすくなる
2. プログラム中のキーワード `type alias` との関連がわかりやすい

1については、例えば
> The type alias `Foo` is ...

という英文があったとき、
> `Foo` という型の別名を

と訳すと
> (`Foo` という型) の別名を

とも読めてしまうし

> 型の別名である `Foo` を

と訳しても、

> 一般に「型」のことを `Foo` とも呼ぶ

という意味にも読めてしまって混乱します。

**Comment by negiboudu** [comment]
私は賛成です😀いいと思います。

**Comment by miyamoen** [comment]
💯
