### ISSUE TITLE
「型を読む」の翻訳漏れ

### ISSUE THREAD

**Issue by negiboudu** [elm-jp/guide#233]
types/reading_types.md（型を読む）の
### 制約付き型変数
の埋め込みREPLのすぐ下に
```
Try expressions like negate 3.1415 and negate (round 3.1415) and negate "hi" ⬆️
```
という英文がそっくりそのまま残っていました。
私がTODOを入れるのを漏らしたようです…ごめんなさい😣

**Comment by arowM** [comment]
漏れを見つけていただいてありがとうございます🥰
