### ISSUE TITLE
提案: カスタム型の補足説明

### ISSUE THREAD

**Issue by arowM** [elm-jp/guide#248]
またElm guideのカスタム型のページでつまづいている初学者の方がいたので、補足説明の記事を書いてみました。
https://qiita.com/arowM/items/a05510b72450355b54dd

Elm guideの翻訳版のカスタム型のページからリンクを貼るのってどう思いますか？
ある程度公益性の高いElm guide翻訳ページから個人が書いた記事にリンクを貼るのはすこしはばかられる気持ちもあります。

**Comment by negiboudu** [comment]
私は良いと思います。特にデメリットが思い浮かびませんでしたし、理解を助けてくれると思いますし。
https://guide.elm-lang.jp/install/
このページの末尾のように訳注の形にしておくと違和感がなさそうです。

**Comment by arowM** [comment]
みなさん、リアクションありがとうございます🥰
訳注としてリンクを貼るプルリクを作成します。
