### ISSUE TITLE
翻訳サポートサービスを活用する

### ISSUE THREAD

**Issue by arowM** [elm-jp/guide#70]
@jinjor さんがdiscordでシェアしてくれた記事で紹介されているような翻訳サポートサービスを使うことを検討しています。
https://qiita.com/wadahiro/items/53f50df7241dc7d61d0c#saas%E3%82%92%E5%88%A9%E7%94%A8%E3%81%97%E3%81%9F%E7%BF%BB%E8%A8%B3%E4%BD%9C%E6%A5%AD

まだ各サービスをサーベイしていませんが、きっと対訳表を簡単に作れたり、同じような言い回しを他の人がどう訳しているかを見つけられるサービスなんだと思います。

このissueでは
* そもそもそういうサービスを導入すべきか （サービス導入のpros/cons)
* ここに挙がっているもの以外にも同種のサービスとして有用そうなものがあるか
* 各サービスの比較検討
などを行います。

**Comment by matsubara0507** [comment]
なにか導入したいけど、いかんせんどれがいいかはさっぱりわからんw
困ったときに参考にできるように、利用してる OSS 知りたいな、調べるか

**Comment by arowM** [comment]
実は「顧客が本当に欲しかったもの」は以下の `npm run pretranslate FILE_TO_TRANSLATE` コマンドなのではないかという気がしてきました。

* 原文を段落ごとにコメントアウトしてくれる
* `about_tranlsate`の対訳表に含まれる用語が原文で使われてたらコメントアウトの下に注釈として対訳をいれてくれる
    (対訳表への用語の追加自体は手作業)
