### ISSUE TITLE
"section" の訳を統一したい

### ISSUE THREAD

**Issue by arowM** [elm-jp/guide#90]
`book/install.md` では "section" を「章」と訳しています。
`book/types/reading_types.md` では "section" を「セクション」と訳しています。

僕は「章」が好きです！
みんなはどっちが好きですか？

**Comment by aratama** [comment]
わたしも『章』が好きです
でもchapter→章、section→節、のイメージなので
節という案もあります

**Comment by arowM** [comment]
完全に同意します！

**Comment by miyamoen** [comment]
章と節で訳し分ける案がいいかなって思いました。

**Comment by matsubara0507** [comment]
章かセクションなら章がいいんですけど、「chapter」ってなんて略します？
(subsection はなかった)

**Comment by arowM** [comment]
@matsubara0507 
「節」か「セクション」だったらどっちがいいですか？

**Comment by aruneko** [comment]
一般的にはChapterが章でSectionが節なのですが、installを翻訳したときに無意識に"章"と書いてしまっていましたね...

**Comment by matsubara0507** [comment]
> 「節」か「セクション」だったらどっちがいいですか？

節ですね、個人的には

**Comment by arowM** [comment]
それであれば、 aratama さんの
>  でもchapter→章、section→節、のイメージなので

で特にみんな異論なさそうですね！
修正PR出します。

**Comment by matsubara0507** [comment]
ここにも書いとく？
https://github.com/elm-jp/guide/blob/master/book/about_translation.md

**Comment by arowM** [comment]
技術用語ではないので、迷ったけど入れたほうがいいかもしれないですね！
それか、読者に示さなくてもいいけど翻訳者の間では共有してしたい訳語の対訳表を別途用意するとか？

**Comment by matsubara0507** [comment]
明示的にするってのもそうなんですけど、#71 で追加された静的チェックでも有効かなと。
